### https://www.netlify.com/docs/netlify-toml-reference/
[build]
base = ""
publish = "public"
command = "make netlify"
# functions = ".functions"

[build.environment]
# zola binary needs to be called from the sites/ directory
# BUILD_BIN = "../zola/zola"
# ZOLA_RELEASE_VER = "0.10.1"
ZOLA_VERSION = "0.10.1"

[context.deploy-preview]
command = "make netlify NETLIFY_DEPLOY_URL=$DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "make netlify NETLIFY_DEPLOY_URL=$DEPLOY_PRIME_URL"

# HEADERS
## https://www.netlify.com/docs/headers-and-basic-auth/
## https://play.netlify.com/headers
### https://securityheaders.io/
### https://scotthelme.co.uk/a-new-security-header-referrer-policy/
### https://scotthelme.co.uk/a-new-security-header-expect-ct/
## Time hints:
## 1h = 3600
## 1d = 86400
## 7d = 604800
## 30d = 2592000
## 180d = 15552000

[[headers]]
for = "/*"
[headers.values]
content-security-policy = "base-uri 'self'; default-src 'self'; script-src 'self' *.cloudfront.net; style-src 'self' 'unsafe-inline' *.cloudfront.net; img-src 'self' data: *.cloudfront.net *.gravatar.com; font-src 'self' *.cloudfront.net; connect-src 'self' *.cloudfront.net; media-src 'self' *.cloudfront.net; worker-src 'self'; manifest-src 'self'; prefetch-src 'self' *.cloudfront.net; object-src 'none'; frame-src 'self' www.youtube-nocookie.com www.youtube.com player.vimeo.com; upgrade-insecure-requests; block-all-mixed-content; report-uri https://markentiertech.report-uri.com/r/d/csp/enforce; report-to cspreport"
expect-ct = "max-age=0, report-uri=https://markentiertech.report-uri.com/r/d/ct/reportOnly"
referrer-policy = "strict-origin-when-cross-origin"
report-to = """{"group":"cspreport","max-age":2592000,"endpoints":[{"url":"https://markentiertech.report-uri.com/r/d/csp/enforce"}"""
x-content-type-options = "nosniff"
x-frame-options = "SAMEORIGIN"
x-github-repo = "https://github.com/markentier/markentier.tech"
x-github-user = "https://github.com/asaaki"
x-xss-protection = "1; mode=block"

# entrypoint file
[[headers]]
for = "/categories/default/index.html"
[headers.values]
cache-control = "max-age=3600"

[[headers]]
for = "/sw-force-update"
[headers.values]
cache-control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/deployment.json"
[headers.values]
cache-control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/sw.js"
[headers.values]
cache-control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/cache.json"
[headers.values]
cache-control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/favicon.ico"
[headers.values]
cache-control = "max-age=15552000"

[[headers]]
for = "/*.svg"
[headers.values]
cache-control = "max-age=15552000"

[[headers]]
for = "/*.png"
[headers.values]
cache-control = "max-age=15552000"

[[headers]]
for = "/*.jpg"
[headers.values]
cache-control = "max-age=15552000"

[[headers]]
for = "/*.woff"
[headers.values]
cache-control = "max-age=15552000"
content-type = "application/font-woff"
access-control-allow-origin = "*"

[[headers]]
for = "/*.woff2"
[headers.values]
cache-control = "max-age=15552000"
content-type = "font/woff2"
access-control-allow-origin = "*"

# REDIRECTS
## https://docs.netlify.com/routing/redirects/

[[redirects]]
from = "/*"
to = "/404/index.html"
status = 404
