### https://www.netlify.com/docs/netlify-toml-reference/
[build]
base = ""
publish = "public"
command = "make netlify"
# functions = ".functions"

[build.environment]
ZOLA_VERSION = "0.12.2"
# in case the netlify provided zola cannot be used:
# zola binary needs to be called from the sites/ directory
# BUILD_BIN = "../zola/zola"

[context.deploy-preview]
command = "make netlify NETLIFY_DEPLOY_URL=$DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "make netlify NETLIFY_DEPLOY_URL=$DEPLOY_PRIME_URL"

# HEADERS
## https://www.netlify.com/docs/headers-and-basic-auth/
## https://play.netlify.com/headers
### https://securityheaders.io/
### https://scotthelme.co.uk/a-new-security-header-referrer-policy/
### https://scotthelme.co.uk/a-new-security-header-expect-ct/
## Time hints:
## 1h = 3600
## 1d = 86400
## 7d = 604800
## 30d = 2592000
## 180d = 15552000
## 365d = 31536000
## 2y = 63072000

## NOTE: Certain automatically injected headers need to be overwritten only
#        by case sensitive header names: Content-Type, not content-type.
#        This is sad, netlify, very sad!

[[headers]]
for = "/*"
[headers.values]
# Casing for STS is important to override value from Netlify:
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

content-security-policy = "base-uri 'self'; default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: *.gravatar.com; font-src 'self'; connect-src 'self'; media-src 'self'; worker-src 'self'; manifest-src 'self'; object-src 'none'; frame-src 'self' www.youtube-nocookie.com www.youtube.com player.vimeo.com; upgrade-insecure-requests; block-all-mixed-content; report-uri https://markentiertech.report-uri.com/r/d/csp/enforce; report-to cspreport"
report-to = """{"group":"cspreport","max-age":2592000,"endpoints":[{"url":"https://markentiertech.report-uri.com/r/d/csp/enforce"}"""

# https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/
feature-policy = "accelerometer 'none'; autoplay 'none'; camera 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; sync-xhr 'none'; usb 'none'; xr-spatial-tracking 'none';"
permission-policy = "accelerometer=(); autoplay=(); camera=(); document-domain=(); encrypted-media=(); fullscreen=(); geolocation=(); gyroscope=(); magnetometer=(); microphone=(); midi=(); payment=(); picture-in-picture=(); sync-xhr=(); usb=(); xr-spatial-tracking=();"
referrer-policy = "strict-origin-when-cross-origin"
expect-ct = "max-age=0, report-uri=https://markentiertech.report-uri.com/r/d/ct/reportOnly"

x-content-type-options = "nosniff"
x-frame-options = "SAMEORIGIN"
x-github-repo = "https://github.com/markentier/markentier.tech"
x-github-user = "https://github.com/asaaki"
x-xss-protection = "1; mode=block"

# does not work :'-(
Server = "markentier.tech"

[[headers]]
for = "/"
[headers.values]
Cache-Control = "max-age=3600"

[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "max-age=3600"

# special treatment for the JSON feed
# be as open as possible (mostly for my personal testing)
[[headers]]
for = "/feed.json"
[headers.values]
Content-Type = "application/feed+json" # casing matters to overwrite the original/automatic value
content-security-policy = "default-src 'self'; script-src *; child-src *; worker-src *"
access-control-max-age = "600"
access-control-allow-origin = "*"
access-control-allow-headers = "*"
access-control-expose-headers = "*"
access-control-allow-methods = "GET,OPTIONS"
# access-control-allow-credentials = "true"

[[headers]]
for = "/sw-force-update"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/deployment.json"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/js/sw.js"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
service-worker-allowed = "/"

[[headers]]
for = "/cache.json"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/js/mtt.js"
[headers.values]
Cache-Control = "max-age=15552000"

[[headers]]
for = "/mtt.css"
[headers.values]
Cache-Control = "max-age=15552000"

[[headers]]
for = "/fonts.css"
[headers.values]
Cache-Control = "max-age=15552000"

[[headers]]
for = "/*.svg"
[headers.values]
Cache-Control = "max-age=15552000"

[[headers]]
for = "/*.avif"
[headers.values]
Content-Type = "image/avif"
content-disposition = "inline"
Cache-Control = "max-age=15552000"

[[headers]]
for = "/*.webp"
[headers.values]
Cache-Control = "max-age=15552000"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "max-age=15552000"

[[headers]]
for = "/*.jpg"
[headers.values]
Cache-Control = "max-age=15552000"

[[headers]]
for = "/*.ico"
[headers.values]
Cache-Control = "max-age=15552000"

[[headers]]
for = "/*.woff"
[headers.values]
Content-Type = "font/woff"
Cache-Control = "max-age=15552000"

[[headers]]
for = "/*.woff2"
[headers.values]
Content-Type = "font/woff2"
Cache-Control = "max-age=15552000"

# it may or may not work, but it's not too important for such extensions
[[headers]]
for = "/*.(ttf|otf|eot|ttc)"
[headers.values]
Cache-Control = "max-age=15552000"
x-note = "cc header based on using a glob pattern"

# REDIRECTS
## https://docs.netlify.com/routing/redirects/

[[redirects]]
from = "/*"
to = "/404/index.html"
status = 404

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "netlify-plugin-debug-cache"
