title = "markentier.tech"
description = "About people, tech, and code"
base_url = "https://markentier.tech"

theme = "mttt"
compile_sass = true

taxonomies = [
  {name = "tags", rss = true},
  {name = "categories", rss = true},
]

generate_rss = true
rss_limit = 10

build_search_index = false
check_external_links = false

[markdown]
highlight_code = true
highlight_theme = "monokai"
render_emoji = true

[extra]
answer = 42
site_base = "markentier.tech"
publisher = "markentier.tech"
author = "Christoph Grabo"
author_nick = "@asaaki"
site_nick = "@markentier_tech"
feed_id = "markentier.tech"
# default keywords
keywords = [
  "code", "people", "humans", "software", "development",
  "diversity", "inclusion",
  "rust", "programming",
  "unicorn", "tech",
]
has_hero = false
image_url = "m.card.1024x512.png"
image_alt = "markentier.tech"
